/* tslint:disable */
/* eslint-disable */
/**
 * Enricher API
 * This is an OpenAPI document for enriched data. It is used by Webhook Features directly.
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FeatureValueType } from './feature-value-type';

/**
 * 
 * @export
 * @interface CacheFeature
 */
export interface CacheFeature {
    /**
     * 
     * @type {string}
     * @memberof CacheFeature
     */
    id: string;
    /**
     * Unique within this application
     * @type {string}
     * @memberof CacheFeature
     */
    key: string;
    /**
     * 
     * @type {FeatureValueType}
     * @memberof CacheFeature
     */
    valueType: FeatureValueType;
    /**
     * used for optimistic locking when renaming a feature
     * @type {number}
     * @memberof CacheFeature
     */
    version: number;
}


