/* tslint:disable */
/* eslint-disable */
/**
 * Enricher API
 * This is an OpenAPI document for enriched data. It is used by Webhook Features directly.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BaseRolloutStrategy } from './base-rollout-strategy';
import { CacheRolloutStrategyAllOf } from './cache-rollout-strategy-all-of';
import { CacheRolloutStrategyAttribute } from './cache-rollout-strategy-attribute';

/**
 * @type CacheRolloutStrategy
 * This is the model for the rollout strategy as required by Dacha and Edge
 * @export
 */
export type CacheRolloutStrategy = BaseRolloutStrategy & CacheRolloutStrategyAllOf;



