/* tslint:disable */
/* eslint-disable */
/**
 * Enricher API
 * This is an OpenAPI document for enriched data. It is used by Webhook Features directly.
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CacheFeature } from './cache-feature';
import { CacheFeatureValue } from './cache-feature-value';

/**
 * A feature and its possible value (which could be null)
 * @export
 * @interface CacheEnvironmentFeature
 */
export interface CacheEnvironmentFeature {
    /**
     * 
     * @type {CacheFeature}
     * @memberof CacheEnvironmentFeature
     */
    feature: CacheFeature;
    /**
     * 
     * @type {CacheFeatureValue}
     * @memberof CacheEnvironmentFeature
     */
    value?: CacheFeatureValue;
}


