/* tslint:disable */
/* eslint-disable */
/**
 * Enricher API
 * This is an OpenAPI document for enriched data. It is used by Webhook Features directly.
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CacheEnvironment } from './cache-environment';
import { CacheEnvironmentFeature } from './cache-environment-feature';
import { PublishAction } from './publish-action';

/**
 * Even a EMPTY message must set all the data to junk as it is an unusual situation
 * @export
 * @interface PublishEnvironment
 */
export interface PublishEnvironment {
    /**
     * 
     * @type {CacheEnvironment}
     * @memberof PublishEnvironment
     */
    environment: CacheEnvironment;
    /**
     * 
     * @type {PublishAction}
     * @memberof PublishEnvironment
     */
    action: PublishAction;
    /**
     * organizationId
     * @type {string}
     * @memberof PublishEnvironment
     */
    oId: string;
    /**
     * portfolioId
     * @type {string}
     * @memberof PublishEnvironment
     */
    pId: string;
    /**
     * applicationId
     * @type {string}
     * @memberof PublishEnvironment
     */
    aId: string;
    /**
     * featureValues
     * @type {Array<CacheEnvironmentFeature>}
     * @memberof PublishEnvironment
     */
    fv: Array<CacheEnvironmentFeature>;
    /**
     * serviceAccounts
     * @type {Array<string>}
     * @memberof PublishEnvironment
     */
    sa: Array<string>;
    /**
     * count
     * @type {number}
     * @memberof PublishEnvironment
     */
    c: number;
}


