/* tslint:disable */
/* eslint-disable */
/**
 * Enricher API
 * This is an OpenAPI document for enriched data. It is used by Webhook Features directly.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Indicates what type of update this is. If CREATE, it is a new record, if UPDATE it updates an existing one, if DELETE you should delete the record. If EMPTY then it indicates there are no records of this type and you shouldn\'t expect to see any further. EMPTY is used to indicate that the Master process is complete.
 * @export
 * @enum {string}
 */
export enum PublishAction {
    Create = 'CREATE',
    Update = 'UPDATE',
    Delete = 'DELETE',
    Empty = 'EMPTY'
}



