/* tslint:disable */
/* eslint-disable */
/**
 * Enricher API
 * This is an OpenAPI document for enriched data. It is used by Webhook Features directly.
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */
export enum RolloutStrategyFieldType {
    String = 'STRING',
    SemanticVersion = 'SEMANTIC_VERSION',
    Number = 'NUMBER',
    Date = 'DATE',
    Datetime = 'DATETIME',
    Boolean = 'BOOLEAN',
    IpAddress = 'IP_ADDRESS'
}



