/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { PersonType } from './person-type';

  /**
* 
* @export
* @class AnemicPerson
*/
export class AnemicPerson  {
  /**
  * 
  * @type {string}
  * @memberof AnemicPerson
  */
  public id: string;
  /**
  * 
  * @type {string}
  * @memberof AnemicPerson
  */
  public name: string;
  /**
  * 
  * @type {PersonType}
  * @memberof AnemicPerson
  */
  public type: PersonType;

  constructor(init?: Partial<AnemicPerson>) {
    Object.assign(this, init);
  }
}


