/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { ApplicationRolloutStrategyAllOf } from './application-rollout-strategy-all-of';
  import { BaseStrategy } from './base-strategy';
  import { BaseUIStrategy } from './base-uistrategy';
  import { RolloutStrategyAttribute } from './rollout-strategy-attribute';

  /**
* 
* @export
* @class ApplicationRolloutStrategy
*/
export class ApplicationRolloutStrategy  {
  /**
  * value between 0 and 1000000 - for four decimal places
  * @type {number}
  * @memberof ApplicationRolloutStrategy
  */
  public percentage?: number | null;
  /**
  * if you don\'t wish to apply percentage based on user id, you can use one or more attributes defined here
  * @type {Array<string>}
  * @memberof ApplicationRolloutStrategy
  */
  public percentageAttributes?: Array<string> | null;
  /**
  * 
  * @type {Array<RolloutStrategyAttribute>}
  * @memberof ApplicationRolloutStrategy
  */
  public attributes?: Array<RolloutStrategyAttribute> | null;
  /**
  * names are unique in a case insensitive fashion
  * @type {string}
  * @memberof ApplicationRolloutStrategy
  */
  public name?: string;
  /**
  * the colour used to display the strategy in the UI. indexed table of background/foreground combos.
  * @type {number}
  * @memberof ApplicationRolloutStrategy
  */
  public colouring?: number | null;
  /**
  * Disable this strategy across all feature values that are using it
  * @type {boolean}
  * @memberof ApplicationRolloutStrategy
  */
  public disabled?: boolean;
  /**
  * url to avatar (if any). Not sent to SDK. Preferably a unicorn.
  * @type {string}
  * @memberof ApplicationRolloutStrategy
  */
  public avatar?: string | null;
  /**
  * unique id of the strategy
  * @type {string}
  * @memberof ApplicationRolloutStrategy
  */
  public id?: string;

  constructor(init?: Partial<ApplicationRolloutStrategy>) {
    Object.assign(this, init);
  }
}


