/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { Environment } from './environment';
  import { Feature } from './feature';
  import { Group } from './group';

  /**
* 
* @export
* @class ApplicationAllOf
*/
export class ApplicationAllOf  {
  /**
  * 
  * @type {string}
  * @memberof ApplicationAllOf
  */
  public id: string;
  /**
  * 
  * @type {string}
  * @memberof ApplicationAllOf
  */
  public name: string;
  /**
  * 
  * @type {string}
  * @memberof ApplicationAllOf
  */
  public description?: string | null;
  /**
  * 
  * @type {string}
  * @memberof ApplicationAllOf
  */
  public portfolioId?: string | null;
  /**
  * 
  * @type {number}
  * @memberof ApplicationAllOf
  */
  public version?: number;
  /**
  * 
  * @type {Array<Group>}
  * @memberof ApplicationAllOf
  */
  public groups?: Array<Group>;
  /**
  * 
  * @type {Array<Feature>}
  * @memberof ApplicationAllOf
  */
  public features?: Array<Feature>;
  /**
  * 
  * @type {Array<Environment>}
  * @memberof ApplicationAllOf
  */
  public environments?: Array<Environment>;
  /**
  * 
  * @type {Date}
  * @memberof ApplicationAllOf
  */
  public whenArchived?: Date | null;

  constructor(init?: Partial<ApplicationAllOf>) {
    Object.assign(this, init);
  }
}


