/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { EnvironmentFeatureValues } from './environment-feature-values';
  import { Feature } from './feature';

  /**
* 
* @export
* @class ApplicationFeatureValues
*/
export class ApplicationFeatureValues  {
  /**
  * 
  * @type {string}
  * @memberof ApplicationFeatureValues
  */
  public applicationId: string;
  /**
  * 
  * @type {Array<Feature>}
  * @memberof ApplicationFeatureValues
  */
  public features: Array<Feature>;
  /**
  * 
  * @type {Array<EnvironmentFeatureValues>}
  * @memberof ApplicationFeatureValues
  */
  public environments: Array<EnvironmentFeatureValues>;
  /**
  * 
  * @type {number}
  * @memberof ApplicationFeatureValues
  */
  public maxFeatures: number;

  constructor(init?: Partial<ApplicationFeatureValues>) {
    Object.assign(this, init);
  }
}


