/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { ApplicationRoleType } from './application-role-type';

  /**
* 
* @export
* @class ApplicationGroupRole
*/
export class ApplicationGroupRole  {
  /**
  * 
  * @type {string}
  * @memberof ApplicationGroupRole
  */
  public applicationId: string;
  /**
  * 
  * @type {string}
  * @memberof ApplicationGroupRole
  */
  public groupId: string;
  /**
  * 
  * @type {Array<ApplicationRoleType>}
  * @memberof ApplicationGroupRole
  */
  public roles: Array<ApplicationRoleType>;

  constructor(init?: Partial<ApplicationGroupRole>) {
    Object.assign(this, init);
  }
}


