/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



  /**
* 
* @export
* @class ApplicationSummary
*/
export class ApplicationSummary  {
  /**
  * 
  * @type {boolean}
  * @memberof ApplicationSummary
  */
  public groupsHavePermission: boolean;
  /**
  * 
  * @type {boolean}
  * @memberof ApplicationSummary
  */
  public serviceAccountsHavePermission: boolean;
  /**
  * 
  * @type {number}
  * @memberof ApplicationSummary
  */
  public featureCount: number;
  /**
  * 
  * @type {number}
  * @memberof ApplicationSummary
  */
  public environmentCount: number;

  constructor(init?: Partial<ApplicationSummary>) {
    Object.assign(this, init);
  }
}


