/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { Person } from './person';

  /**
* 
* @export
* @class Audit
*/
export class Audit  {
  /**
  * 
  * @type {Person}
  * @memberof Audit
  */
  public createdBy?: Person;
  /**
  * 
  * @type {Person}
  * @memberof Audit
  */
  public updatedBy?: Person;
  /**
  * 
  * @type {Date}
  * @memberof Audit
  */
  public whenCreated?: Date;
  /**
  * 
  * @type {Date}
  * @memberof Audit
  */
  public whenUpdated?: Date;

  constructor(init?: Partial<Audit>) {
    Object.assign(this, init);
  }
}


