/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { BaseRolloutStrategyAttribute } from './base-rollout-strategy-attribute';

  /**
* if the feature in an environment is different from its default, this will be the reason for it. a rollout strategy is defined at the Application level and then applied to a specific feature value. When they are copied to the cache layer they are cloned and the feature value for that strategy is inserted into the clone and those are published.
* @export
* @class BaseRolloutStrategy
*/
export class BaseRolloutStrategy  {
  /**
  * 
  * @type {string}
  * @memberof BaseRolloutStrategy
  */
  public id?: string;
  /**
  * value between 0 and 1000000 - for four decimal places
  * @type {number}
  * @memberof BaseRolloutStrategy
  */
  public percentage?: number;
  /**
  * if you don\'t wish to apply percentage based on user id, you can use one or more attributes defined here
  * @type {Array<string>}
  * @memberof BaseRolloutStrategy
  */
  public percentageAttributes?: Array<string>;
  /**
  * when we attach the RolloutStrategy for Dacha or SSE this lets us push the value out. Only visible in SDK and SSE Edge.
  * @type {any}
  * @memberof BaseRolloutStrategy
  */
  public value?: any | null;
  /**
  * 
  * @type {Array<BaseRolloutStrategyAttribute>}
  * @memberof BaseRolloutStrategy
  */
  public attributes?: Array<BaseRolloutStrategyAttribute>;

  constructor(init?: Partial<BaseRolloutStrategy>) {
    Object.assign(this, init);
  }
}


