/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



  /**
* 
* @export
* @class BaseUIStrategy
*/
export class BaseUIStrategy  {
  /**
  * names are unique in a case insensitive fashion
  * @type {string}
  * @memberof BaseUIStrategy
  */
  public name?: string;
  /**
  * the colour used to display the strategy in the UI. indexed table of background/foreground combos.
  * @type {number}
  * @memberof BaseUIStrategy
  */
  public colouring?: number | null;
  /**
  * Disable this strategy across all feature values that are using it
  * @type {boolean}
  * @memberof BaseUIStrategy
  */
  public disabled?: boolean;
  /**
  * url to avatar (if any). Not sent to SDK. Preferably a unicorn.
  * @type {string}
  * @memberof BaseUIStrategy
  */
  public avatar?: string | null;

  constructor(init?: Partial<BaseUIStrategy>) {
    Object.assign(this, init);
  }
}


