/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { BaseRolloutStrategyAllOf } from './base-rollout-strategy-all-of';
  import { BaseStrategy } from './base-strategy';
  import { RolloutStrategyAttribute } from './rollout-strategy-attribute';

  /**
* 
* @export
* @class BaseRolloutStrategy
*/
export class BaseRolloutStrategy  {
  /**
  * value between 0 and 1000000 - for four decimal places
  * @type {number}
  * @memberof BaseRolloutStrategy
  */
  public percentage?: number | null;
  /**
  * if you don\'t wish to apply percentage based on user id, you can use one or more attributes defined here
  * @type {Array<string>}
  * @memberof BaseRolloutStrategy
  */
  public percentageAttributes?: Array<string> | null;
  /**
  * 
  * @type {Array<RolloutStrategyAttribute>}
  * @memberof BaseRolloutStrategy
  */
  public attributes?: Array<RolloutStrategyAttribute> | null;
  /**
  * when we attach the RolloutStrategy for Dacha or SSE this lets us push the value out. Only visible in SDK and SSE Edge.
  * @type {any}
  * @memberof BaseRolloutStrategy
  */
  public value?: any | null;

  constructor(init?: Partial<BaseRolloutStrategy>) {
    Object.assign(this, init);
  }
}


