/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



  /**
* 
* @export
* @class CacheRefreshResponse
*/
export class CacheRefreshResponse  {
  /**
  * 
  * @type {number}
  * @memberof CacheRefreshResponse
  */
  public applicationsRefreshed?: number | null;
  /**
  * 
  * @type {number}
  * @memberof CacheRefreshResponse
  */
  public portfoliosRefreshed?: number | null;
  /**
  * 
  * @type {number}
  * @memberof CacheRefreshResponse
  */
  public environmentsRefreshed?: number | null;
  /**
  * 
  * @type {number}
  * @memberof CacheRefreshResponse
  */
  public serviceAccountsRefreshed?: number | null;

  constructor(init?: Partial<CacheRefreshResponse>) {
    Object.assign(this, init);
  }
}


