/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { PersonType } from './person-type';

  /**
* 
* @export
* @class CreatePersonDetails
*/
export class CreatePersonDetails  {
  /**
  * Can be null if a service account
  * @type {string}
  * @memberof CreatePersonDetails
  */
  public email?: string | null;
  /**
  * 
  * @type {PersonType}
  * @memberof CreatePersonDetails
  */
  public personType: PersonType;
  /**
  * Can be null if a service account
  * @type {string}
  * @memberof CreatePersonDetails
  */
  public name?: string | null;
  /**
  * 
  * @type {Array<string>}
  * @memberof CreatePersonDetails
  */
  public groupIds?: Array<string> | null;

  constructor(init?: Partial<CreatePersonDetails>) {
    Object.assign(this, init);
  }
}


