/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



  /**
* 
* @export
* @class CreatePortfolio
*/
export class CreatePortfolio  {
  /**
  * 
  * @type {string}
  * @memberof CreatePortfolio
  */
  public name: string;
  /**
  * 
  * @type {string}
  * @memberof CreatePortfolio
  */
  public description: string | null;

  constructor(init?: Partial<CreatePortfolio>) {
    Object.assign(this, init);
  }
}


