/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { FeatureValueType } from './feature-value-type';

  /**
* Only used when creating a new feature
* @export
* @class CreateFeature
*/
export class CreateFeature  {
  /**
  * Unique within this application
  * @type {string}
  * @memberof CreateFeature
  */
  public key: string;
  /**
  * use this in code, as then people cannot guess your new features from their names
  * @type {string}
  * @memberof CreateFeature
  */
  public alias?: string | null;
  /**
  * 
  * @type {string}
  * @memberof CreateFeature
  */
  public link?: string | null;
  /**
  * description if any
  * @type {string}
  * @memberof CreateFeature
  */
  public name: string;
  /**
  * 
  * @type {FeatureValueType}
  * @memberof CreateFeature
  */
  public valueType: FeatureValueType;
  /**
  * should the config remain invisible to users without secret permission
  * @type {boolean}
  * @memberof CreateFeature
  */
  public secret?: boolean | null;
  /**
  * 
  * @type {string}
  * @memberof CreateFeature
  */
  public description?: string | null;
  /**
  * Metadata that may need to be stored. Intended for ADK use. No data limit on FHOS. 10k on SaaS. (stored as CLOB)
  * @type {string}
  * @memberof CreateFeature
  */
  public metaData?: string | null;

  constructor(init?: Partial<CreateFeature>) {
    Object.assign(this, init);
  }
}


