/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { RolloutStrategy } from './rollout-strategy';
  import { RolloutStrategyViolation } from './rollout-strategy-violation';

  /**
* 
* @export
* @class CustomRolloutStrategyViolation
*/
export class CustomRolloutStrategyViolation  {
  /**
  * 
  * @type {RolloutStrategy}
  * @memberof CustomRolloutStrategyViolation
  */
  public strategy?: RolloutStrategy;
  /**
  * 
  * @type {Array<RolloutStrategyViolation>}
  * @memberof CustomRolloutStrategyViolation
  */
  public violations?: Array<RolloutStrategyViolation>;

  constructor(init?: Partial<CustomRolloutStrategyViolation>) {
    Object.assign(this, init);
  }
}


