/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { FeatureValue } from './feature-value';
  import { RoleType } from './role-type';

  /**
* 
* @export
* @class EnvironmentFeatureValues
*/
export class EnvironmentFeatureValues  {
  /**
  * 
  * @type {string}
  * @memberof EnvironmentFeatureValues
  */
  public environmentId?: string;
  /**
  * 
  * @type {string}
  * @memberof EnvironmentFeatureValues
  */
  public environmentName?: string;
  /**
  * 
  * @type {string}
  * @memberof EnvironmentFeatureValues
  */
  public priorEnvironmentId?: string;
  /**
  * the values of the features depending on access
  * @type {Array<FeatureValue>}
  * @memberof EnvironmentFeatureValues
  */
  public features?: Array<FeatureValue>;
  /**
  * the roles of this person in this environment
  * @type {Array<RoleType>}
  * @memberof EnvironmentFeatureValues
  */
  public roles?: Array<RoleType>;

  constructor(init?: Partial<EnvironmentFeatureValues>) {
    Object.assign(this, init);
  }
}


