/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { EnvironmentGroupRole } from './environment-group-role';
  import { Feature } from './feature';
  import { ServiceAccountPermission } from './service-account-permission';

  /**
* 
* @export
* @class EnvironmentAllOf
*/
export class EnvironmentAllOf  {
  /**
  * 
  * @type {string}
  * @memberof EnvironmentAllOf
  */
  public id?: string;
  /**
  * 
  * @type {string}
  * @memberof EnvironmentAllOf
  */
  public applicationId?: string;
  /**
  * 
  * @type {string}
  * @memberof EnvironmentAllOf
  */
  public name: string;
  /**
  * 
  * @type {string}
  * @memberof EnvironmentAllOf
  */
  public priorEnvironmentId?: string;
  /**
  * 
  * @type {number}
  * @memberof EnvironmentAllOf
  */
  public version?: number;
  /**
  * 
  * @type {string}
  * @memberof EnvironmentAllOf
  */
  public description?: string;
  /**
  * is this a production environment?
  * @type {boolean}
  * @memberof EnvironmentAllOf
  */
  public production?: boolean;
  /**
  * 
  * @type {Array<EnvironmentGroupRole>}
  * @memberof EnvironmentAllOf
  */
  public groupRoles?: Array<EnvironmentGroupRole>;
  /**
  * 
  * @type {Array<Feature>}
  * @memberof EnvironmentAllOf
  */
  public features?: Array<Feature>;
  /**
  * 
  * @type {Record<string, string>}
  * @memberof EnvironmentAllOf
  */
  public environmentInfo?: Record<string, string> | null;
  /**
  * 
  * @type {Array<ServiceAccountPermission>}
  * @memberof EnvironmentAllOf
  */
  public serviceAccountPermission?: Array<ServiceAccountPermission>;
  /**
  * 
  * @type {Date}
  * @memberof EnvironmentAllOf
  */
  public whenArchived?: Date;

  constructor(init?: Partial<EnvironmentAllOf>) {
    Object.assign(this, init);
  }
}


