/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { RoleType } from './role-type';

  /**
* 
* @export
* @class EnvironmentPermission
*/
export class EnvironmentPermission  {
  /**
  * 
  * @type {string}
  * @memberof EnvironmentPermission
  */
  public id: string;
  /**
  * 
  * @type {string}
  * @memberof EnvironmentPermission
  */
  public name: string;
  /**
  * 
  * @type {Array<RoleType>}
  * @memberof EnvironmentPermission
  */
  public roles: Array<RoleType>;

  constructor(init?: Partial<EnvironmentPermission>) {
    Object.assign(this, init);
  }
}


