/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { FeatureGroupUpdateFeature } from './feature-group-update-feature';
  import { GroupRolloutStrategy } from './group-rollout-strategy';

  /**
* An update, everything is optional, we will only update what we update
* @export
* @class FeatureGroupUpdate
*/
export class FeatureGroupUpdate  {
  /**
  * 
  * @type {string}
  * @memberof FeatureGroupUpdate
  */
  public id: string;
  /**
  * allow changing the name
  * @type {string}
  * @memberof FeatureGroupUpdate
  */
  public name?: string | null;
  /**
  * 
  * @type {string}
  * @memberof FeatureGroupUpdate
  */
  public description?: string | null;
  /**
  * allow updating the features
  * @type {Array<FeatureGroupUpdateFeature>}
  * @memberof FeatureGroupUpdate
  */
  public features?: Array<FeatureGroupUpdateFeature> | null;
  /**
  * We only honour the first one
  * @type {Array<GroupRolloutStrategy>}
  * @memberof FeatureGroupUpdate
  */
  public strategies?: Array<GroupRolloutStrategy> | null;
  /**
  * 
  * @type {number}
  * @memberof FeatureGroupUpdate
  */
  public order?: number | null;
  /**
  * 
  * @type {number}
  * @memberof FeatureGroupUpdate
  */
  public version: number;

  constructor(init?: Partial<FeatureGroupUpdate>) {
    Object.assign(this, init);
  }
}


