/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



  /**
* 
* @export
* @class FeatureGroupUpdateFeature
*/
export class FeatureGroupUpdateFeature  {
  /**
  * 
  * @type {string}
  * @memberof FeatureGroupUpdateFeature
  */
  public id: string;
  /**
  * value (if any) associated with this feature for this strategy
  * @type {any}
  * @memberof FeatureGroupUpdateFeature
  */
  public value?: any | null;

  constructor(init?: Partial<FeatureGroupUpdateFeature>) {
    Object.assign(this, init);
  }
}


