/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { FeatureGroupListFeature } from './feature-group-list-feature';

  /**
* 
* @export
* @class FeatureGroupListGroup
*/
export class FeatureGroupListGroup  {
  /**
  * 
  * @type {string}
  * @memberof FeatureGroupListGroup
  */
  public id: string;
  /**
  * 
  * @type {number}
  * @memberof FeatureGroupListGroup
  */
  public order: number;
  /**
  * 
  * @type {string}
  * @memberof FeatureGroupListGroup
  */
  public name: string;
  /**
  * 
  * @type {string}
  * @memberof FeatureGroupListGroup
  */
  public description?: string;
  /**
  * 
  * @type {string}
  * @memberof FeatureGroupListGroup
  */
  public environmentName: string;
  /**
  * 
  * @type {string}
  * @memberof FeatureGroupListGroup
  */
  public environmentId: string;
  /**
  * 
  * @type {number}
  * @memberof FeatureGroupListGroup
  */
  public version: number;
  /**
  * 
  * @type {boolean}
  * @memberof FeatureGroupListGroup
  */
  public hasStrategy: boolean;
  /**
  * 
  * @type {Array<FeatureGroupListFeature>}
  * @memberof FeatureGroupListGroup
  */
  public features: Array<FeatureGroupListFeature>;

  constructor(init?: Partial<FeatureGroupListGroup>) {
    Object.assign(this, init);
  }
}


