/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { FeatureGroupFeature } from './feature-group-feature';
  import { GroupRolloutStrategy } from './group-rollout-strategy';

  /**
* 
* @export
* @class FeatureGroup
*/
export class FeatureGroup  {
  /**
  * 
  * @type {string}
  * @memberof FeatureGroup
  */
  public id: string;
  /**
  * 
  * @type {string}
  * @memberof FeatureGroup
  */
  public name: string;
  /**
  * 
  * @type {number}
  * @memberof FeatureGroup
  */
  public order: number;
  /**
  * 
  * @type {string}
  * @memberof FeatureGroup
  */
  public description?: string;
  /**
  * 
  * @type {number}
  * @memberof FeatureGroup
  */
  public version: number;
  /**
  * 
  * @type {string}
  * @memberof FeatureGroup
  */
  public environmentId: string;
  /**
  * 
  * @type {string}
  * @memberof FeatureGroup
  */
  public environmentName: string;
  /**
  * Whether or not this group should be disabled
  * @type {boolean}
  * @memberof FeatureGroup
  */
  public disabled?: boolean;
  /**
  * 
  * @type {Array<FeatureGroupFeature>}
  * @memberof FeatureGroup
  */
  public features: Array<FeatureGroupFeature>;
  /**
  * We only honour the first one
  * @type {Array<GroupRolloutStrategy>}
  * @memberof FeatureGroup
  */
  public strategies?: Array<GroupRolloutStrategy> | null;

  constructor(init?: Partial<FeatureGroup>) {
    Object.assign(this, init);
  }
}


