/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { FeatureHistoryValue } from './feature-history-value';

  /**
* 
* @export
* @class FeatureHistoryItem
*/
export class FeatureHistoryItem  {
  /**
  * 
  * @type {string}
  * @memberof FeatureHistoryItem
  */
  public envId?: string;
  /**
  * 
  * @type {string}
  * @memberof FeatureHistoryItem
  */
  public featureValueId?: string;
  /**
  * 
  * @type {string}
  * @memberof FeatureHistoryItem
  */
  public featureId?: string;
  /**
  * 
  * @type {Array<FeatureHistoryValue>}
  * @memberof FeatureHistoryItem
  */
  public history?: Array<FeatureHistoryValue>;

  constructor(init?: Partial<FeatureHistoryItem>) {
    Object.assign(this, init);
  }
}


