/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { AnemicPerson } from './anemic-person';
  import { RolloutStrategy } from './rollout-strategy';

  /**
* 
* @export
* @class FeatureHistoryValue
*/
export class FeatureHistoryValue  {
  /**
  * 
  * @type {number}
  * @memberof FeatureHistoryValue
  */
  public version?: number;
  /**
  * 
  * @type {number}
  * @memberof FeatureHistoryValue
  */
  public versionFrom?: number | null;
  /**
  * When it was created
  * @type {Date}
  * @memberof FeatureHistoryValue
  */
  public when?: Date;
  /**
  * 
  * @type {AnemicPerson}
  * @memberof FeatureHistoryValue
  */
  public who?: AnemicPerson;
  /**
  * the value, no type is passed back
  * @type {any}
  * @memberof FeatureHistoryValue
  */
  public value?: any | null;
  /**
  * 
  * @type {boolean}
  * @memberof FeatureHistoryValue
  */
  public locked?: boolean;
  /**
  * 
  * @type {boolean}
  * @memberof FeatureHistoryValue
  */
  public retired?: boolean;
  /**
  * 
  * @type {Array<RolloutStrategy>}
  * @memberof FeatureHistoryValue
  */
  public rolloutStrategies?: Array<RolloutStrategy>;

  constructor(init?: Partial<FeatureHistoryValue>) {
    Object.assign(this, init);
  }
}


