/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { FeatureValueType } from './feature-value-type';

  /**
* exists simply to hold the name of the feature as it exists across all environments
* @export
* @class Feature
*/
export class Feature  {
  /**
  * 
  * @type {string}
  * @memberof Feature
  */
  public id?: string | null;
  /**
  * Unique within this application
  * @type {string}
  * @memberof Feature
  */
  public key?: string;
  /**
  * use this in code, as then people cannot guess your new features from their names
  * @type {string}
  * @memberof Feature
  */
  public alias?: string | null;
  /**
  * 
  * @type {string}
  * @memberof Feature
  */
  public link?: string | null;
  /**
  * description if any
  * @type {string}
  * @memberof Feature
  */
  public name: string;
  /**
  * 
  * @type {FeatureValueType}
  * @memberof Feature
  */
  public valueType?: FeatureValueType;
  /**
  * used for optimistic locking when renaming a feature
  * @type {number}
  * @memberof Feature
  */
  public version?: number;
  /**
  * 
  * @type {Date}
  * @memberof Feature
  */
  public whenArchived?: Date | null;
  /**
  * should the config remain invisible to users without secret permission
  * @type {boolean}
  * @memberof Feature
  */
  public secret?: boolean | null;
  /**
  * 
  * @type {string}
  * @memberof Feature
  */
  public description?: string | null;
  /**
  * Metadata that may need to be stored. Intended for ADK use. No data limit on FHOS. 10k on SaaS. (stored as CLOB)
  * @type {string}
  * @memberof Feature
  */
  public metaData?: string | null;

  constructor(init?: Partial<Feature>) {
    Object.assign(this, init);
  }
}


