/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { ApplicationGroupRole } from './application-group-role';
  import { EnvironmentGroupRole } from './environment-group-role';
  import { Person } from './person';

  /**
* 
* @export
* @class GroupAllOf
*/
export class GroupAllOf  {
  /**
  * 
  * @type {string}
  * @memberof GroupAllOf
  */
  public id?: string;
  /**
  * is this an admin group?
  * @type {boolean}
  * @memberof GroupAllOf
  */
  public admin?: boolean;
  /**
  * 
  * @type {string}
  * @memberof GroupAllOf
  */
  public portfolioId?: string;
  /**
  * this will be the organisation this group belongs to at the top level, or if a portfolio group, the organisation of the portfolio
  * @type {string}
  * @memberof GroupAllOf
  */
  public organizationId?: string;
  /**
  * 
  * @type {number}
  * @memberof GroupAllOf
  */
  public version?: number;
  /**
  * 
  * @type {string}
  * @memberof GroupAllOf
  */
  public name: string;
  /**
  * 
  * @type {Array<Person>}
  * @memberof GroupAllOf
  */
  public members?: Array<Person>;
  /**
  * 
  * @type {Array<ApplicationGroupRole>}
  * @memberof GroupAllOf
  */
  public applicationRoles?: Array<ApplicationGroupRole>;
  /**
  * 
  * @type {Array<EnvironmentGroupRole>}
  * @memberof GroupAllOf
  */
  public environmentRoles?: Array<EnvironmentGroupRole>;
  /**
  * 
  * @type {Date}
  * @memberof GroupAllOf
  */
  public whenArchived?: Date;

  constructor(init?: Partial<GroupAllOf>) {
    Object.assign(this, init);
  }
}


