/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



  /**
* 
* @export
* @class HiddenEnvironments
*/
export class HiddenEnvironments  {
  /**
  * 
  * @type {Array<string>}
  * @memberof HiddenEnvironments
  */
  public environmentIds?: Array<string>;

  constructor(init?: Partial<HiddenEnvironments>) {
    Object.assign(this, init);
  }
}


