/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



  /**
* 
* @export
* @class IdentityProviderInfo
*/
export class IdentityProviderInfo  {
  /**
  * 
  * @type {string}
  * @memberof IdentityProviderInfo
  */
  public buttonIcon: string;
  /**
  * 
  * @type {string}
  * @memberof IdentityProviderInfo
  */
  public buttonBackgroundColor: string;
  /**
  * 
  * @type {string}
  * @memberof IdentityProviderInfo
  */
  public buttonText: string;

  constructor(init?: Partial<IdentityProviderInfo>) {
    Object.assign(this, init);
  }
}


