/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { Audit } from './audit';
  import { Group } from './group';
  import { OrganizationAllOf } from './organization-all-of';
  import { Person } from './person';
  import { Portfolio } from './portfolio';

  /**
* 
* @export
* @class Organization
*/
export class Organization  {
  /**
  * 
  * @type {Person}
  * @memberof Organization
  */
  public createdBy?: Person | null;
  /**
  * 
  * @type {Person}
  * @memberof Organization
  */
  public updatedBy?: Person | null;
  /**
  * 
  * @type {Date}
  * @memberof Organization
  */
  public whenCreated?: Date | null;
  /**
  * 
  * @type {Date}
  * @memberof Organization
  */
  public whenUpdated?: Date | null;
  /**
  * 
  * @type {string}
  * @memberof Organization
  */
  public id?: string;
  /**
  * 
  * @type {number}
  * @memberof Organization
  */
  public version?: number | null;
  /**
  * 
  * @type {string}
  * @memberof Organization
  */
  public name: string;
  /**
  * ignored
  * @type {boolean}
  * @memberof Organization
    * @deprecated
  */
  public admin?: boolean | null;
  /**
  * If provided, the browser should redirect to this URL to authenticate
  * @type {string}
  * @memberof Organization
  */
  public authorizationUrl?: string | null;
  /**
  * 
  * @type {Group}
  * @memberof Organization
  */
  public orgGroup?: Group | null;
  /**
  * 
  * @type {Array<Portfolio>}
  * @memberof Organization
  */
  public portfolios?: Array<Portfolio> | null;
  /**
  * 
  * @type {Date}
  * @memberof Organization
  */
  public whenArchived?: Date | null;

  constructor(init?: Partial<Organization>) {
    Object.assign(this, init);
  }
}


