/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { Group } from './group';
  import { Portfolio } from './portfolio';

  /**
* 
* @export
* @class OrganizationAllOf
*/
export class OrganizationAllOf  {
  /**
  * 
  * @type {string}
  * @memberof OrganizationAllOf
  */
  public id?: string;
  /**
  * 
  * @type {number}
  * @memberof OrganizationAllOf
  */
  public version?: number;
  /**
  * 
  * @type {string}
  * @memberof OrganizationAllOf
  */
  public name: string;
  /**
  * 
  * @type {boolean}
  * @memberof OrganizationAllOf
  */
  public admin?: boolean;
  /**
  * If provided, the browser should redirect to this URL to authenticate
  * @type {string}
  * @memberof OrganizationAllOf
  */
  public authorizationUrl?: string;
  /**
  * 
  * @type {Group}
  * @memberof OrganizationAllOf
  */
  public orgGroup?: Group;
  /**
  * 
  * @type {Array<Portfolio>}
  * @memberof OrganizationAllOf
  */
  public portfolios?: Array<Portfolio>;
  /**
  * 
  * @type {Date}
  * @memberof OrganizationAllOf
  */
  public whenArchived?: Date;

  constructor(init?: Partial<OrganizationAllOf>) {
    Object.assign(this, init);
  }
}


