/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



  /**
* 
* @export
* @class OutstandingRegistration
*/
export class OutstandingRegistration  {
  /**
  * 
  * @type {string}
  * @memberof OutstandingRegistration
  */
  public id: string;
  /**
  * 
  * @type {string}
  * @memberof OutstandingRegistration
  */
  public token: string;
  /**
  * 
  * @type {boolean}
  * @memberof OutstandingRegistration
  */
  public expired: boolean;

  constructor(init?: Partial<OutstandingRegistration>) {
    Object.assign(this, init);
  }
}


