/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { Group } from './group';
  import { PersonId } from './person-id';
  import { PersonInfo } from './person-info';
  import { PersonType } from './person-type';

  /**
* 
* @export
* @class Person
*/
export class Person  {
  /**
  * 
  * @type {PersonId}
  * @memberof Person
  */
  public id?: PersonId;
  /**
  * 
  * @type {string}
  * @memberof Person
  */
  public name?: string;
  /**
  * 
  * @type {string}
  * @memberof Person
  */
  public email?: string;
  /**
  * 
  * @type {PersonType}
  * @memberof Person
  */
  public personType?: PersonType;
  /**
  * 
  * @type {string}
  * @memberof Person
  */
  public other?: string;
  /**
  * 
  * @type {string}
  * @memberof Person
  */
  public source?: string;
  /**
  * 
  * @type {number}
  * @memberof Person
  */
  public version?: number;
  /**
  * 
  * @type {boolean}
  * @memberof Person
  */
  public passwordRequiresReset?: boolean;
  /**
  * 
  * @type {Array<Group>}
  * @memberof Person
  */
  public groups?: Array<Group>;
  /**
  * 
  * @type {Date}
  * @memberof Person
  */
  public whenArchived?: Date;
  /**
  * This is the timestamp in UTC when they last logged into the system
  * @type {Date}
  * @memberof Person
  */
  public whenLastAuthenticated?: Date;
  /**
  * This is the timestamp in UTC when they last made a request to the system on their most recent login. If it is null it means they have no current token or have never logged in.
  * @type {Date}
  * @memberof Person
  */
  public whenLastSeen?: Date;
  /**
  * 
  * @type {Array<PersonInfo>}
  * @memberof Person
  */
  public additional?: Array<PersonInfo>;

  constructor(init?: Partial<Person>) {
    Object.assign(this, init);
  }
}


