/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { Application } from './application';
  import { Group } from './group';

  /**
* 
* @export
* @class PortfolioAllOf
*/
export class PortfolioAllOf  {
  /**
  * 
  * @type {string}
  * @memberof PortfolioAllOf
  */
  public id: string;
  /**
  * 
  * @type {string}
  * @memberof PortfolioAllOf
  */
  public name: string;
  /**
  * 
  * @type {string}
  * @memberof PortfolioAllOf
  */
  public description?: string | null;
  /**
  * 
  * @type {number}
  * @memberof PortfolioAllOf
  */
  public version: number;
  /**
  * 
  * @type {string}
  * @memberof PortfolioAllOf
  */
  public organizationId?: string | null;
  /**
  * 
  * @type {Array<Group>}
  * @memberof PortfolioAllOf
  */
  public groups?: Array<Group>;
  /**
  * 
  * @type {Array<Application>}
  * @memberof PortfolioAllOf
  */
  public applications?: Array<Application>;
  /**
  * 
  * @type {Date}
  * @memberof PortfolioAllOf
  */
  public whenArchived?: Date | null;

  constructor(init?: Partial<PortfolioAllOf>) {
    Object.assign(this, init);
  }
}


