/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



  /**
* 
* @export
* @class RegistrationUrl
*/
export class RegistrationUrl  {
  /**
  * 
  * @type {string}
  * @memberof RegistrationUrl
  */
  public registrationUrl?: string | null;
  /**
  * 
  * @type {string}
  * @memberof RegistrationUrl
  */
  public personId: string;
  /**
  * 
  * @type {string}
  * @memberof RegistrationUrl
  */
  public token: string;

  constructor(init?: Partial<RegistrationUrl>) {
    Object.assign(this, init);
  }
}


