/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { BaseRolloutStrategyAttribute } from './base-rollout-strategy-attribute';
  import { RolloutStrategyAttributeAllOf } from './rollout-strategy-attribute-all-of';
  import { RolloutStrategyAttributeConditional } from './rollout-strategy-attribute-conditional';
  import { RolloutStrategyFieldType } from './rollout-strategy-field-type';

  /**
* 
* @export
* @class RolloutStrategyAttribute
*/
export class RolloutStrategyAttribute  {
  /**
  * 
  * @type {RolloutStrategyAttributeConditional}
  * @memberof RolloutStrategyAttribute
  */
  public conditional?: RolloutStrategyAttributeConditional;
  /**
  * 
  * @type {string}
  * @memberof RolloutStrategyAttribute
  */
  public fieldName?: string;
  /**
  * the value(s) associated with this rule
  * @type {Array<any>}
  * @memberof RolloutStrategyAttribute
  */
  public values?: Array<any>;
  /**
  * 
  * @type {RolloutStrategyFieldType}
  * @memberof RolloutStrategyAttribute
  */
  public type?: RolloutStrategyFieldType;
  /**
  * A temporary id used only when validating. Saving strips these out as they are not otherwise necessary
  * @type {string}
  * @memberof RolloutStrategyAttribute
  */
  public id?: string;

  constructor(init?: Partial<RolloutStrategyAttribute>) {
    Object.assign(this, init);
  }
}


