/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



  /**
* 
* @export
* @class RolloutStrategyAttributeAllOf
*/
export class RolloutStrategyAttributeAllOf  {
  /**
  * A temporary id used only when validating. Saving strips these out as they are not otherwise necessary
  * @type {string}
  * @memberof RolloutStrategyAttributeAllOf
  */
  public id?: string;

  constructor(init?: Partial<RolloutStrategyAttributeAllOf>) {
    Object.assign(this, init);
  }
}


