/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



  /**
* 
* @export
* @class RolloutStrategyInstance
*/
export class RolloutStrategyInstance  {
  /**
  * This is copied from the shared rollout strategy on return, it is read only from the client perspective
  * @type {string}
  * @memberof RolloutStrategyInstance
  */
  public name?: string;
  /**
  * 
  * @type {string}
  * @memberof RolloutStrategyInstance
  */
  public strategyId?: string;
  /**
  * the value for this rollout strategy for this feature value
  * @type {any}
  * @memberof RolloutStrategyInstance
  */
  public value?: any | null;
  /**
  * 
  * @type {boolean}
  * @memberof RolloutStrategyInstance
  */
  public disabled?: boolean;

  constructor(init?: Partial<RolloutStrategyInstance>) {
    Object.assign(this, init);
  }
}


