/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { RolloutStrategyAttribute } from './rollout-strategy-attribute';

  /**
* 
* @export
* @class RolloutStrategyAllOf
*/
export class RolloutStrategyAllOf  {
  /**
  * names are unique in a case insensitive fashion
  * @type {string}
  * @memberof RolloutStrategyAllOf
  */
  public name: string;
  /**
  * the colour used to display the strategy in the UI. indexed table of background/foreground combos.
  * @type {number}
  * @memberof RolloutStrategyAllOf
  */
  public colouring?: number;
  /**
  * url to avatar (if any). Not sent to SDK. Preferably a unicorn.
  * @type {string}
  * @memberof RolloutStrategyAllOf
  */
  public avatar?: string;
  /**
  * 
  * @type {Array<RolloutStrategyAttribute>}
  * @memberof RolloutStrategyAllOf
  */
  public attributes?: Array<RolloutStrategyAttribute>;

  constructor(init?: Partial<RolloutStrategyAllOf>) {
    Object.assign(this, init);
  }
}


