/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { RolloutStrategy } from './rollout-strategy';
  import { RolloutStrategyInstance } from './rollout-strategy-instance';

  /**
* A collection of strategies to validate together to see if it violates any rules
* @export
* @class RolloutStrategyValidationRequest
*/
export class RolloutStrategyValidationRequest  {
  /**
  * 
  * @type {Array<RolloutStrategy>}
  * @memberof RolloutStrategyValidationRequest
  */
  public customStrategies?: Array<RolloutStrategy>;
  /**
  * 
  * @type {Array<RolloutStrategyInstance>}
  * @memberof RolloutStrategyValidationRequest
  */
  public sharedStrategies?: Array<RolloutStrategyInstance>;

  constructor(init?: Partial<RolloutStrategyValidationRequest>) {
    Object.assign(this, init);
  }
}


