/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { RolloutStrategyViolationType } from './rollout-strategy-violation-type';

  /**
* 
* @export
* @class RolloutStrategyViolation
*/
export class RolloutStrategyViolation  {
  /**
  * The id of the attribute (if any)
  * @type {string}
  * @memberof RolloutStrategyViolation
  */
  public id?: string;
  /**
  * 
  * @type {RolloutStrategyViolationType}
  * @memberof RolloutStrategyViolation
  */
  public violation: RolloutStrategyViolationType;

  constructor(init?: Partial<RolloutStrategyViolation>) {
    Object.assign(this, init);
  }
}


