/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { CustomRolloutStrategyViolation } from './custom-rollout-strategy-violation';
  import { RolloutStrategyCollectionViolationType } from './rollout-strategy-collection-violation-type';
  import { SharedRolloutStrategyViolation } from './shared-rollout-strategy-violation';

  /**
* 
* @export
* @class RolloutStrategyValidationResponse
*/
export class RolloutStrategyValidationResponse  {
  /**
  * 
  * @type {Array<CustomRolloutStrategyViolation>}
  * @memberof RolloutStrategyValidationResponse
  */
  public customStategyViolations?: Array<CustomRolloutStrategyViolation>;
  /**
  * 
  * @type {Array<SharedRolloutStrategyViolation>}
  * @memberof RolloutStrategyValidationResponse
  */
  public sharedStrategyViolations?: Array<SharedRolloutStrategyViolation>;
  /**
  * 
  * @type {Array<RolloutStrategyCollectionViolationType>}
  * @memberof RolloutStrategyValidationResponse
  */
  public violations?: Array<RolloutStrategyCollectionViolationType>;

  constructor(init?: Partial<RolloutStrategyValidationResponse>) {
    Object.assign(this, init);
  }
}


