/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { RoleType } from './role-type';
  import { ServiceAccount } from './service-account';

  /**
* this represents a specific set of permissions for a SDK service account in an environment
* @export
* @class ServiceAccountPermission
*/
export class ServiceAccountPermission  {
  /**
  * 
  * @type {string}
  * @memberof ServiceAccountPermission
  */
  public id?: string | null;
  /**
  * 
  * @type {Array<RoleType>}
  * @memberof ServiceAccountPermission
  */
  public permissions: Array<RoleType>;
  /**
  * 
  * @type {ServiceAccount}
  * @memberof ServiceAccountPermission
  */
  public serviceAccount?: ServiceAccount | null;
  /**
  * 
  * @type {string}
  * @memberof ServiceAccountPermission
  */
  public environmentId: string;
  /**
  * Optional if they have chosen includeSdkUrl
  * @type {string}
  * @memberof ServiceAccountPermission
  */
  public sdkUrlClientEval?: string | null;
  /**
  * Optional if they have chosen includeSdkUrl
  * @type {string}
  * @memberof ServiceAccountPermission
  */
  public sdkUrlServerEval?: string | null;

  constructor(init?: Partial<ServiceAccountPermission>) {
    Object.assign(this, init);
  }
}


