/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { IdentityProviderInfo } from './identity-provider-info';
  import { Organization } from './organization';

  /**
* 
* @export
* @class SetupResponse
*/
export class SetupResponse  {
  /**
  * 
  * @type {Organization}
  * @memberof SetupResponse
  */
  public organization?: Organization;
  /**
  * 
  * @type {Array<string>}
  * @memberof SetupResponse
  */
  public providers?: Array<string>;
  /**
  * 
  * @type {Record<string, IdentityProviderInfo>}
  * @memberof SetupResponse
  */
  public providerInfo?: Record<string, IdentityProviderInfo>;
  /**
  * 
  * @type {Record<string, string>}
  * @memberof SetupResponse
  */
  public capabilityInfo?: Record<string, string>;
  /**
  * Set if there is only one external provider and no local. Allows immediate redirect to provider. It assumes it will be used immediate (e.g. state in oauth2 url)
  * @type {string}
  * @memberof SetupResponse
  */
  public redirectUrl?: string;

  constructor(init?: Partial<SetupResponse>) {
    Object.assign(this, init);
  }
}


