/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



  /**
* 
* @export
* @class SetupSiteAdmin
*/
export class SetupSiteAdmin  {
  /**
  * 
  * @type {string}
  * @memberof SetupSiteAdmin
  */
  public portfolio: string;
  /**
  * 
  * @type {string}
  * @memberof SetupSiteAdmin
  */
  public organizationName: string;
  /**
  * User\'s email or blank if using oauth/saml
  * @type {string}
  * @memberof SetupSiteAdmin
  */
  public emailAddress?: string | null;
  /**
  * User\'s password or blank if using oauth/saml
  * @type {string}
  * @memberof SetupSiteAdmin
  */
  public password?: string | null;
  /**
  * user\'s name. Will be take from external provider if using oauth/saml
  * @type {string}
  * @memberof SetupSiteAdmin
  */
  public name?: string | null;
  /**
  * If the site is using external providers, this is the key of the provider chosen. If there is only one, it can be blank.
  * @type {string}
  * @memberof SetupSiteAdmin
  */
  public authProvider?: string | null;

  constructor(init?: Partial<SetupSiteAdmin>) {
    Object.assign(this, init);
  }
}


