/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { RolloutStrategyInstance } from './rollout-strategy-instance';
  import { RolloutStrategyViolation } from './rollout-strategy-violation';

  /**
* 
* @export
* @class SharedRolloutStrategyViolation
*/
export class SharedRolloutStrategyViolation  {
  /**
  * 
  * @type {RolloutStrategyInstance}
  * @memberof SharedRolloutStrategyViolation
  */
  public strategy?: RolloutStrategyInstance;
  /**
  * 
  * @type {Array<RolloutStrategyViolation>}
  * @memberof SharedRolloutStrategyViolation
  */
  public violation?: Array<RolloutStrategyViolation>;

  constructor(init?: Partial<SharedRolloutStrategyViolation>) {
    Object.assign(this, init);
  }
}


