/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



  /**
* 
* @export
* @class ThinGroupRolloutStrategy
*/
export class ThinGroupRolloutStrategy  {
  /**
  * 
  * @type {string}
  * @memberof ThinGroupRolloutStrategy
  */
  public name?: string;
  /**
  * The value for this strategy, currently always a string
  * @type {any}
  * @memberof ThinGroupRolloutStrategy
  */
  public value?: any | null;

  constructor(init?: Partial<ThinGroupRolloutStrategy>) {
    Object.assign(this, init);
  }
}


