/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { Person } from './person';

  /**
* 
* @export
* @class TokenizedPerson
*/
export class TokenizedPerson  {
  /**
  * 
  * @type {string}
  * @memberof TokenizedPerson
  */
  public accessToken?: string | null;
  /**
  * 
  * @type {string}
  * @memberof TokenizedPerson
  */
  public refreshToken?: string | null;
  /**
  * 
  * @type {string}
  * @memberof TokenizedPerson
  */
  public redirectUrl?: string | null;
  /**
  * 
  * @type {Record<string, string>}
  * @memberof TokenizedPerson
  */
  public capabilityInfo?: Record<string, string> | null;
  /**
  * 
  * @type {Person}
  * @memberof TokenizedPerson
  */
  public person?: Person | null;

  constructor(init?: Partial<TokenizedPerson>) {
    Object.assign(this, init);
  }
}


