/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



  /**
* 
* @export
* @class UpdatePerson
*/
export class UpdatePerson  {
  /**
  * 
  * @type {string}
  * @memberof UpdatePerson
  */
  public name?: string | null;
  /**
  * 
  * @type {string}
  * @memberof UpdatePerson
  */
  public email?: string | null;
  /**
  * This keeps track of which person version we are updating in case the user tries to update an old record
  * @type {number}
  * @memberof UpdatePerson
  */
  public version: number;
  /**
  * 
  * @type {Array<string>}
  * @memberof UpdatePerson
  */
  public groups?: Array<string> | null;
  /**
  * 
  * @type {boolean}
  * @memberof UpdatePerson
  */
  public unarchive?: boolean | null;

  constructor(init?: Partial<UpdatePerson>) {
    Object.assign(this, init);
  }
}


