/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



  /**
* 
* @export
* @class UserCredentials
*/
export class UserCredentials  {
  /**
  * 
  * @type {string}
  * @memberof UserCredentials
  */
  public email: string;
  /**
  * 
  * @type {string}
  * @memberof UserCredentials
  */
  public password: string;

  constructor(init?: Partial<UserCredentials>) {
    Object.assign(this, init);
  }
}


