/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


  import { WebhookSummaryItem } from './webhook-summary-item';

  /**
* 
* @export
* @class WebhookSummary
*/
export class WebhookSummary  {
  /**
  * 
  * @type {number}
  * @memberof WebhookSummary
  */
  public max: number;
  /**
  * 
  * @type {Array<WebhookSummaryItem>}
  * @memberof WebhookSummary
  */
  public results: Array<WebhookSummaryItem>;

  constructor(init?: Partial<WebhookSummary>) {
    Object.assign(this, init);
  }
}


