/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



  /**
* webhook data
* @export
* @class WebhookDetail
*/
export class WebhookDetail  {
  /**
  * 
  * @type {Date}
  * @memberof WebhookDetail
  */
  public whenSent?: Date;
  /**
  * The status of the webhook call
  * @type {number}
  * @memberof WebhookDetail
  */
  public status: number;
  /**
  * 
  * @type {string}
  * @memberof WebhookDetail
  */
  public method: string;
  /**
  * 
  * @type {string}
  * @memberof WebhookDetail
  */
  public sourceSystem?: string;
  /**
  * 
  * @type {string}
  * @memberof WebhookDetail
  */
  public deliveredDataCloudEventType?: string;
  /**
  * 
  * @type {string}
  * @memberof WebhookDetail
  */
  public cloudEventType: string;
  /**
  * 
  * @type {string}
  * @memberof WebhookDetail
  */
  public content?: string;
  /**
  * The URL requested, only if Admin
  * @type {string}
  * @memberof WebhookDetail
  */
  public url?: string | null;
  /**
  * The headers we set on the outbound call, only if Admin
  * @type {Record<string, string>}
  * @memberof WebhookDetail
  */
  public outboundHeaders?: Record<string, string> | null;
  /**
  * The headers that came back, only if Admin
  * @type {Record<string, string>}
  * @memberof WebhookDetail
  */
  public incomingHeaders?: Record<string, string> | null;
  /**
  * The body as a string if any, truncated to 1k
  * @type {string}
  * @memberof WebhookDetail
  */
  public result?: string;

  constructor(init?: Partial<WebhookDetail>) {
    Object.assign(this, init);
  }
}


