/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



  /**
* 
* @export
* @class WebhookSummaryItem
*/
export class WebhookSummaryItem  {
  /**
  * event id as stored in the database (not webhook cloudevent id)
  * @type {string}
  * @memberof WebhookSummaryItem
  */
  public id: string;
  /**
  * webhook type, empty if the filter is specified as it is just repeated data
  * @type {string}
  * @memberof WebhookSummaryItem
  */
  public type?: string;
  /**
  * POST, PUT, etc
  * @type {string}
  * @memberof WebhookSummaryItem
  */
  public method: string;
  /**
  * When the hook was posted
  * @type {Date}
  * @memberof WebhookSummaryItem
  */
  public whenSent: Date;
  /**
  * HTTP status code
  * @type {number}
  * @memberof WebhookSummaryItem
  */
  public status: number;

  constructor(init?: Partial<WebhookSummaryItem>) {
    Object.assign(this, init);
  }
}


