/* tslint:disable */
/* eslint-disable */
/**
 * Feature Messaging API
 * This is an OpenAPI document for featurehub messaging data. It is used to publish feature updates to messaging listeners.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BaseRolloutStrategyAllOf
 */
export interface BaseRolloutStrategyAllOf {
    /**
     * when we attach the RolloutStrategy for Dacha or SSE this lets us push the value out. Only visible in SDK and SSE Edge.
     * @type {any}
     * @memberof BaseRolloutStrategyAllOf
     */
    value?: any | null;
}


