/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { Environment } from '../models';
// @ts-ignore
import { UpdateEnvironment } from '../models';
// @ts-ignore
import { ObjectSerializer } from '../models';
/**
 * Environment2ServiceApi - axios parameter creator
 * @export
 */
export const Environment2ServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Update an environment
         * @param {string} eid The id of the environment to find
         * @param {UpdateEnvironment} updateEnvironment 
         * @param {boolean} [includeAcls] Include the acls attached to this environment
         * @param {boolean} [includeFeatures] Include the features attached to this environment
         * @param {boolean} [includeDetails] Include all environment details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEnvironmentV2: async (eid: string, updateEnvironment: UpdateEnvironment, includeAcls?: boolean, includeFeatures?: boolean, includeDetails?: boolean, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'eid' is not null or undefined
            if (eid === null || eid === undefined) {
                throw new RequiredError('eid','Required parameter eid was null or undefined when calling updateEnvironmentV2.');
            }
            // verify required parameter 'updateEnvironment' is not null or undefined
            if (updateEnvironment === null || updateEnvironment === undefined) {
                throw new RequiredError('updateEnvironment','Required parameter updateEnvironment was null or undefined when calling updateEnvironmentV2.');
            }
            const localVarPath = `/mr-api/environment/{eid}/v2`
                .replace(`{${"eid"}}`, encodeURIComponent(String(eid)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (includeAcls !== undefined) {
                localVarQueryParameter['includeAcls'] = includeAcls;
            }

            if (includeFeatures !== undefined) {
                localVarQueryParameter['includeFeatures'] = includeFeatures;
            }

            if (includeDetails !== undefined) {
                localVarQueryParameter['includeDetails'] = includeDetails;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof updateEnvironment !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(updateEnvironment !== undefined ? ObjectSerializer.serialize(updateEnvironment, 'UpdateEnvironment') : {}) : (updateEnvironment || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * Environment2ServiceApi - functional programming interface
 * @export
 */
export const Environment2ServiceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Update an environment
         * @param {string} eid The id of the environment to find
         * @param {UpdateEnvironment} updateEnvironment 
         * @param {boolean} [includeAcls] Include the acls attached to this environment
         * @param {boolean} [includeFeatures] Include the features attached to this environment
         * @param {boolean} [includeDetails] Include all environment details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateEnvironmentV2(eid: string, updateEnvironment: UpdateEnvironment, includeAcls?: boolean, includeFeatures?: boolean, includeDetails?: boolean, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Environment>> {
            const localVarAxiosArgs = await Environment2ServiceApiAxiosParamCreator(configuration).updateEnvironmentV2(eid, updateEnvironment, includeAcls, includeFeatures, includeDetails, options);
            return (axios: AxiosInstance = (configuration?.axiosInstance || globalAxios), basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
          return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * Environment2ServiceApi - factory interface
 * @export
 */
export const Environment2ServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Update an environment
         * @param {string} eid The id of the environment to find
         * @param {UpdateEnvironment} updateEnvironment 
         * @param {boolean} [includeAcls] Include the acls attached to this environment
         * @param {boolean} [includeFeatures] Include the features attached to this environment
         * @param {boolean} [includeDetails] Include all environment details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEnvironmentV2(eid: string, updateEnvironment: UpdateEnvironment, includeAcls?: boolean, includeFeatures?: boolean, includeDetails?: boolean, options?: any): AxiosPromise<Environment> {
            return Environment2ServiceApiFp(configuration).updateEnvironmentV2(eid, updateEnvironment, includeAcls, includeFeatures, includeDetails, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Environment2ServiceApi - object-oriented interface
 * @export
 * @class Environment2ServiceApi
 * @extends {BaseAPI}
 */
export class Environment2ServiceApi extends BaseAPI {
    /**
     * Update an environment
     * @param {string} eid The id of the environment to find
     * @param {UpdateEnvironment} updateEnvironment 
     * @param {boolean} [includeAcls] Include the acls attached to this environment
     * @param {boolean} [includeFeatures] Include the features attached to this environment
     * @param {boolean} [includeDetails] Include all environment details
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof Environment2ServiceApi
     */
    public updateEnvironmentV2(eid: string, updateEnvironment: UpdateEnvironment, includeAcls?: boolean, includeFeatures?: boolean, includeDetails?: boolean, options?: any): AxiosPromise<Environment> {
        return Environment2ServiceApiFp(this.configuration).updateEnvironmentV2(eid, updateEnvironment, includeAcls, includeFeatures, includeDetails, options).then((request) => request(this.axios, this.basePath));
    }
}
