/* tslint:disable */
/* eslint-disable */
/**
 * ManagementResourceApi
 * This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ApplicationVersionInfo } from '../models';
// @ts-ignore
import { ObjectSerializer } from '../models';
/**
 * InfoServiceApi - axios parameter creator
 * @export
 */
export const InfoServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Gets information as to what this server is.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInfoVersion: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/info/version`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InfoServiceApi - functional programming interface
 * @export
 */
export const InfoServiceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Gets information as to what this server is.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInfoVersion(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApplicationVersionInfo>> {
            const localVarAxiosArgs = await InfoServiceApiAxiosParamCreator(configuration).getInfoVersion(options);
            return (axios: AxiosInstance = (configuration?.axiosInstance || globalAxios), basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
          return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * InfoServiceApi - factory interface
 * @export
 */
export const InfoServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Gets information as to what this server is.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInfoVersion(options?: any): AxiosPromise<ApplicationVersionInfo> {
            return InfoServiceApiFp(configuration).getInfoVersion(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InfoServiceApi - object-oriented interface
 * @export
 * @class InfoServiceApi
 * @extends {BaseAPI}
 */
export class InfoServiceApi extends BaseAPI {
    /**
     * Gets information as to what this server is.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InfoServiceApi
     */
    public getInfoVersion(options?: any): AxiosPromise<ApplicationVersionInfo> {
        return InfoServiceApiFp(this.configuration).getInfoVersion(options).then((request) => request(this.axios, this.basePath));
    }
}
